{{- if and .Values.controller.podDisruptionBudget.enabled (not .Values.nodeComponentOnly) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fsx-csi-controller
  namespace: kube-system
  labels:
    {{- include "aws-fsx-csi-driver.labels" . | nindent 4 }} 
spec:
  selector:
    matchLabels:
      app: fsx-csi-controller
      {{- include "aws-fsx-csi-driver.selectorLabels" . | nindent 6 }} 
  {{- if .Values.controller.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .Values.controller.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  {{- end }}
  {{- if le (.Values.controller.replicaCount | int) 2 }}
  maxUnavailable: 1
  {{- else }}
  minAvailable: 2
  {{- end }}
{{- end -}}